name: eahe2025
description: EAHE 2025 mobile app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  http: ^1.2.2
  csv: ^6.0.0
  intl: ^0.19.0
  crypto: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/speakers/
    
